print('Enter 4 numbers')
x = input()
y = input()
z = input()
d = input()
f = int(x) + int(y)
h = int(z) + int(d)
k = int(f) / int(h)
print('the sum of the first two numbers', f)
print('the sum of the second two numbers', h)
print('quotient of these sums', k)
